### PR TITLE
ImmutableMap does not allow null values :disappointed:

### LINKED ISSUE #65: Null committersToIgnore producing exception
If no committersToIgnore has been send in json to rest api configuration endpoint, the following error is produced:

```
2017-08-28 11:08:29,271 ERROR [http-nio-7990-exec-74] sysmgr @2Z9SKDx668x9099120x5 54.174.231.94,10.242.84.215 "PUT /rest/webhook/1.0/projects/org/repos/repo/
configurations HTTP/1.1" c.a.s.i.r.e.DefaultUnhandledExceptionMapperHelper Unhandled exception while processing REST request: "PUT /rest/webhook/1.0/projects/org/repos/repo/configurations HTTP/1.1"
java.lang.NullPointerException: null value in entry: COMMITTERS_TO_IGNORE=null
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[guava-18.0.jar:na]
at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[guava-18.0.jar:na]
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[guava-18.0.jar:na]
at nl.topicus.bitbucket.persistence.WebHookConfigurationDao.createOrUpdateWebHookConfiguration(WebHookConfigurationDao.java:76) ~[bitbucket-webhooks-1.5.0.jar:na]
at nl.topicus.bitbucket.persistence.WebHookConfigurationDao.createOrUpdateWebHookConfiguration(WebHookConfigurationDao.java:50) ~[bitbucket-webhooks-1.5.0.jar:na]
at nl.topicus.bitbucket.api.WebhookResource.createOrUpdateWebhook(WebhookResource.java:66) ~[bitbucket-webhooks-1.5.0.jar:na]
at nl.topicus.bitbucket.api.WebhookResource.createWebhook(WebhookResource.java:40) ~[bitbucket-webhooks-1.5.0.jar:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472695158000.jar:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472695158000.jar:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472695158000.jar:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472695158000.jar:na]
at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472695158000.jar:na]
at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92) [analytics-client-5.2.9_1472695158000.jar:na]
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.9_1472695158000.jar:na]
at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.onSuccess(StashAuthenticationFilter.java:220) [classes/:na]
at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:103) [classes/:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na
]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1472695158000.jar:na]
at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.11-0002_1472695158000.jar:na]
at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38) [analytics-client-5.2.9_1472695158000.jar:na]
at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.9_1472695158000.jar:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:86) ~[bitbucket-service-impl-4.9.1.jar:na]
at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[classes/:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
... 232 frames trimmed
```

I think `null` should be interpreted as an empty string. This causing the following issue https://issues.jenkins-ci.org/browse/JENKINS-45548?focusedCommentId=312030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-312030

### PR DESCRIPTION
**Pull request by casz**
fixes #65 

With a test case and check for possible null.

### CODE REVIEW

File: src/main/java/nl/topicus/bitbucket/persistence/WebHookConfigurationDao.java [hunk 1]
```diff
@@ -60,6 +60,7 @@ public WebHookConfiguration createOrUpdateWebHookConfiguration(Repository rep, S
                                                                    boolean isPrRescoped, boolean isPrMerged, boolean isPrReopened,
                                                                    boolean isPrUpdated, boolean isPrCreated, boolean isPrCommented, boolean isBuildStatus) {
         WebHookConfiguration webHookConfiguration = id == null ? null : getWebHookConfiguration(id);
+        committersToIgnore = committersToIgnore == null ? "" : committersToIgnore;
```
Comment (casz) [inline src/main/java/nl/topicus/bitbucket/persistence/WebHookConfigurationDao.java]: ActiveObject turns empty strings into null according to [`docs`](https://ecosystem.atlassian.net/wiki/spaces/AO/pages/16744506/Simplified+SQL+type+mappings)

Comment (bturner) [reply src/main/java/nl/topicus/bitbucket/persistence/WebHookConfigurationDao.java]: It has to, unfortunately, because Oracle handles `""` and `NULL` differently.

Comment (casz) [reply src/main/java/nl/topicus/bitbucket/persistence/WebHookConfigurationDao.java]: Only noted as a good thing 👍
