### PR TITLE
check build state for null pointer

### LINKED ISSUE #88: Error while processing asynchronous task
I am seeing the following in my logs, can you please let me know what this is for?

```
2017-12-14 11:17:05,230 ERROR [threadpool:thread-2]  c.a.s.i.c.DefaultTransferableStateManager Error while processing asynchronous task
java.lang.NullPointerException: null
	at nl.topicus.bitbucket.api.PullRequestListener.lambda$onBuildStatusSetEvent$1(PullRequestListener.java:212)
	at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	... 1 frame trimmed
```

### PR DESCRIPTION
**Pull request by casz**
fixes #88

### CODE REVIEW

File: src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java [hunk 1]
```diff
@@ -209,14 +210,20 @@ public void onBuildStatusSetEvent(BuildStatusSetEvent event) throws IOException
...
-            IndexedCommit commit = commitIndex.getCommit(event.getCommitId());
-            if (commit != null) {
-                for (Repository repo : commit.getRepositories()){
-                    buildStatusEvent.setRepository(Models.createRepository(repo, applicationPropertiesService));
-                    sendEvents(buildStatusEvent, repo, EventType.BUILD_STATUS);
+            BuildState buildState = event.getBuildStatus().getState();
+            String url = event.getBuildStatus().getUrl();
+            // Due to https://jira.atlassian.com/browse/BSERV-10986 we have to check for null
+            //noinspection ConstantConditions
+            if (buildState != null || url != null) {
```
Comment (bturner) [inline src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: Using `||` here means if `buildState` is `null` but `url` isn't, you'll get a `NullPointerException` on line 219 when you call `toString()`.

Comment (casz) [reply src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: Right mistake obviously 👍

**Comment by casz** [comment]
thanks for the good eyes @bturner I merged it too quickly... did a direct commit since it was minor in this case: https://github.com/Eernie/bitbucket-webhooks-plugin/commit/cdeb50dde8c7680a612a36a75902e2a6345d6243

File: src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java [hunk 2]
```diff
@@ -209,14 +210,20 @@ public void onBuildStatusSetEvent(BuildStatusSetEvent event) throws IOException
...
             BuildStatusEvent buildStatusEvent = new BuildStatusEvent();
-            buildStatusEvent.setCommit(event.getCommitId());
-            buildStatusEvent.setStatus(event.getBuildStatus().getState().toString());
-            buildStatusEvent.setUrl(event.getBuildStatus().getUrl());
-            IndexedCommit commit = commitIndex.getCommit(event.getCommitId());
-            if (commit != null) {
-                for (Repository repo : commit.getRepositories()){
-                    buildStatusEvent.setRepository(Models.createRepository(repo, applicationPropertiesService));
-                    sendEvents(buildStatusEvent, repo, EventType.BUILD_STATUS);
+            BuildState buildState = event.getBuildStatus().getState();
```
Comment (bturner) [inline src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: A slightly different approach to this change would be to pull out the values _before_ you call `executorService.submit`, which will reduce the likelihood of a `null`. (Why? Because with the current approach there are 2 delays: One between when the system raises the event and when your `@EventListener` is run, and a second between when you add it to the executor and when it runs.) If you pull the check up it initializes the ActiveObjects proxy earlier, cutting out one of those delays, and increasing the likelihood that the backing row is still present.

Something like this, maybe:

```java
public void onBuildStatusSetEvent(BuildStatusSetEvent event) throws IOException
{
    BuildStatus buildStatus = event.getBuildStatus();
    BuildState buildState = buildStatus.getState();
    String url = buildStatus.getUrl(); 
    // Due to https://jira.atlassian.com/browse/BSERV-10986 we have to check for null 
    //noinspection ConstantConditions 
    if (buildState == null || url == null) {
        return;
    }

    executorService.submit(() -> { 
        BuildStatusEvent buildStatusEvent = new BuildStatusEvent(); 
        buildStatusEvent.setCommit(event.getCommitId()); 
        buildStatusEvent.setStatus(buildState.toString()); 
        buildStatusEvent.setUrl(url); 
        IndexedCommit commit = commitIndex.getCommit(event.getCommitId()); 
        if (commit != null) { 
            for (Repository repo : commit.getRepositories()) { 
                buildStatusEvent.setRepository(Models.createRepository(repo, applicationPropertiesService)); 
                sendEvents(buildStatusEvent, repo, EventType.BUILD_STATUS); 
            } 
        } 
    });
}
```

Comment (casz) [reply src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: Definitely merged it too quickly I completely agree with you. You are putting me to shame 😞 I just put something together quickly. Will make a PR

**Comment by bturner** [comment]
Thanks for doing this, @casz, and apologies for the hassle. I appreciate you updating your code to smooth over our bug.

**Comment by casz** [comment]
@bturner I only wanted to fix it till I knew the bug was being fixed 😅 otherwise I am just making it worse for the others that might integrate with Bitbucket. Only way to get internal stuff fixed is enough attention/issues 😝

File: src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java (hunk 2 above)
Comment (bturner) [reply src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: Certainly not my intention to shame! Again, my thanks for you looking into it so quickly

Comment (casz) [reply src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java]: Lack of better word 😐
